server:
  port: 8084
base-url:
  context: /com/v1.0/citymgt
app:
  host: localhost:8084

custom:
  validation:
    serial-number:
      max-length: 100

logging:
  request:
    shouldLogInfo: true
  response:
    shouldLogInfo: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

log:
  identifierKey: UUID
  isDebug: true
  isInfo: true

request:
  id-key: requestId

spring.datasource.url: jdbc:mysql://localhost/city_mgt?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.password: root
spring.datasource.username: root
spring.datasource.maxActive: 20
spring.datasource.maxIdle: 10
spring.datasource.maxWait: 10000
spring.jpa.generate-ddl: true
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
hibernate:
  jdbc:
    time_zone: UTC

importing-path: D:\Personal\poc\kuehne+Nagel\BE\temp

#properties related to JWT token creation
security:
  jwt:
    sign:
      key: BymMoFgfyZTFNQhGGX52E6tHvqkeuvKQvdsfrerre323409NNJWDKFWfdse673mfdkNHHFPQkd9389NB923CNLKSknl9849NCKS2836510NMLCKosdklmqISHJpjsHikm
    expiretime:
      access:
        token:
          millisecond: 9000000 #150mins
      refresh:
        token:
          hour: 720 #30days


user:
  info:
    transfer:
      synchronous:
        key: skdsklc97%^&80><


password:
  encoder:
    rounds: 10
time:
  zone: Asia/Colombo


